version: "3"

services:
        db:
                image: mariadb
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: ThisIsMyPassword2310_core
                ports:
                        - 3301:3306
                volumes:
                        - ./db:/var/lib/mysql
